### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by mdrxy** [tophtucker/Orient-BONUS-2.0#1]
There are some great archival photos in here (I looked at all of them).

Have you considered handing any over to Special Collections? It feels like there is a void in their collection of on-the-ground/amateur visual perspectives of campus from the period of time this covers.

**Comment by tophtucker** [comment]
Glad someone's looking at this! That's a great idea. Are you a student? You should reach out to them! 😅 I haven't been in touch with them in like a decade…

**Comment by tophtucker** [comment]
(if not id be happy to)

**Comment by mdrxy** [comment]
Yep, rising senior. I'll reach out and see if they have any interest, though I imagine there may be some aspects about this collection that are challenging (numerous unidentifiable authors/attribution, etc.)

**Comment by tophtucker** [comment]
i may be able to help w some of that. cc me! tophtucker@gmail
